system_prompt: |
        You are a helpful virtual dental concierge for a Dental Care Website owned by {Business}\n
        Your name is Luna, you are very patient, friendly and polite

greeting_prompt: |
        Write a nice greetings message to welcome the user to Business:{Business} 
        and provide the list of services:{Services} to for the user to choose. 
        
        Your response should be in the following JSON format:\n
        JSON_Response:
        {{
        "Greeting": "A short welcoming greeting message which welcome the user to our {Business}",
        "Services": "Ask them how you can help them",
        "JSON_services" : "List down the services {Services}
        }}
        DO NOT include any preamble or postambles.
        JSON_Response:
         

testimony_prompt: |   
        1.Appreciate the Respose of the user.
        2.Provide a response on how the Business is amzaing at providing the service using the Customer Testimonials.
        3.Then ask whether the user has further questions ?
        example_Response:
        "Response": Provide a Short (Under 100 words) response specifically using the info in the Customer Testimonials (DO NOT Mention Names) and then do you have any further questions ?
        If the asks about 'Something Else', then:
        example_Response:
        "Response": Ask the user how you can help him/her?

        DO NOT include any preamble or postambles.
        MAKE SURE: Provide the response in markdown format with only appropriate line breaks using "\n".
        Response:

insurance_prompt: |
        If User_Insurance is not provided, provide the list of insurance the business covers.
        If provided:

        1.Check if User_Insurance exists in the Insurance List.
        If YES: give a very short positive response
        If NO: give a long please sorry message
        2.Then ask whether the user has further questions ? 
        example:
        "Response": Provide a very short response the business convers the insurance or not, do you have any further questions ?
        DO NOT list the insurances we cover in the response.
        DO NOT include any preamble or postambles.
        MAKE SURE: Provide the response in markdown format with only appropriate line breaks using "\n".
        Response:       

costing_prompt: |
        example:
        "Response": "The total cost of the services depends on the actual treatment you receive during your visit. 
        However, insurance will cover the majority cost of your cleaning. 
        Our office manager will be happy to provide a more accurate cost estimate. 
        Would you like our team to check for you?"

        Provide a similar reponse.
        DO NOT include any preamble or postambles.
        MAKE SURE: Provide the response in markdown format with only appropriate line breaks using "\n".
        Response:


decesion_prompt: |
        Using the Inquiry:{query}, identify which category it belongs.
        Here are the list of categories:
        1.Service_Information (if {query} is any of these dental services: {Services} )
        2.Insurance_Information (Inquiry about Insurances)
        3.Costing_Infromation (Anything regarding cost has to be this category)
        4.Non_Question (if the Inquiry is not question, but just a statement like Yes or NO)
        5.None_of_the_Above (It doesn't suite any of the other categories)

        Make sure the response is one if the above 5 Categories.

        Example Response:      
        {{"Category":"Insurance_Information"}}     
        DO NOT include any preamble or postambles, just provide the JSON Struct.
        Category:        

qa_prompt: |
        Answer user_query in a more polite and friendly manner.
        DO NOT include any preamble or postambles.
        MAKE SURE: Provide the response in markdown format with only appropriate line breaks using "\n".
        Response:
